### PR TITLE
Development

### PR DESCRIPTION
**Pull request by rvvergara**
Refactored app:

- Installed webpack
- Converted Class based OO code into Factories and functional style
- Implication of using webpack is streamlining directories
- Redesigned architecture to, as much as possible, follow SOLID principles

### CODE REVIEW

**Comment by talihomz** [comment]
## Great JS implementation of TicTacToe!
---

Hi @rvvergara @dipto0321. Great TCC implementation! I was able to run the game, but can't beat it on hard mode 😩. 

As for the code, the structure is really confusing and all over the place! I couldn't follow it clearly. Here is why:
1. The [index file](https://github.com/dipto0321/tic-tac-toe/blob/development/src/js/index.js) handles adding of event listeners on the DOM, yet we have a `domUtils` [file](https://github.com/dipto0321/tic-tac-toe/blob/development/src/js/utils/domUtils.js). Why not move all DOM functionality here?
2. Both the [callbacks](https://github.com/dipto0321/tic-tac-toe/blob/development/src/js/utils/callbacks.js) and [helpers](https://github.com/dipto0321/tic-tac-toe/blob/development/src/js/helpers.js) file also manupilate the DOM separately, meaning they are taking on more responsibilities, which belong to the `domUtils` file.
3. I feel like the [game controls](https://github.com/dipto0321/tic-tac-toe/blob/67155d107ee102f7ff13db202908ff12e331a297/src/js/helpers.js#L57) helper isn't a helper at all, rather a class of its own that manages the game.

**Comment by rvvergara** [comment]
Hi @talihomz ,

Thanks for the review again. OMG, I forgot to push the updated version. 
1. I already deleted helper.js. Therefore, no more need for the fns inside it. 
2. I renamed domUtil.js into gameDisplay.js because the function inside it does only that - display the board and other elements
3. The callback.js file is composed of all the related callbacks to events
4. I just maintained the event listening adding on index.js in order to not anymore write functions for them (it will be redundant to do those).

**Comment by talihomz** [comment]
Hi @rvvergara! Awesome improvements to this so far. Its a 👍 from me!

**Comment by rvvergara** [comment]
Thank you thank you @talihomz! :) We learned a lot from your reviews..

**Pull request merged**
